/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.graphy;

import java.net.URLClassLoader;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        openPreWindow(primaryStage);
    }

    private void openMainWindow(Stage primaryStage) {
        try {

        } catch (Exception e) {

        }
    }

    private void openPreWindow(Stage primaryStage) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/PreWindow.fxml"));
            Pane rootNode = loader.load();
            Scene scene = new Scene(rootNode);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
