/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.graphy;

import java.net.URLClassLoader;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage preStage) throws Exception{
        PreWindowController preWindowController = new PreWindowController(preStage);
        preWindowController.getStage().show();
    }
}
