/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphy;

import Graphy.Graph.Edge;
import Graphy.Graph.ValueHandler;
import Graphy.Graph.Vertex;

public class App {

    public static void main(String[] args) {

    }
}
